# Change these first
owner: WeTrackIT-NT # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Website
    url: https://www.wetrackit.com.au
  - name: Tracking Dashboard
    url: https://app.wetrackit.com.au
  - name: Devices - Teltonika Support
    check: "tcp-ping"
    url: data.wetrackit.com.au
    port: 6027
  - name: Devices - TopFlyTech Support
    check: "tcp-ping"
    url: data.wetrackit.com.au
    port: 6047
  - name: LEGACY Tracking Dashboard
    url: https://dashboard.wetrackit.com.au

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.wetrackit.com.au
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: We Track IT
  introTitle: "*We Track IT** is the Terrtory's leading telematics provider"
navbar:
    - title: Website
      href: https://www.wetrackit.com.au
    - title: Dashboard
      href: https://app.wetrackit.com.au
    - title: iOS Download
      href: https://apps.apple.com/au/app/we-track-it/id6449930972
    - title: Android Download
      href: https://play.google.com/store/apps/details?id=com.WeTrackITclient.android

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
