# Change these first
owner: WeTrackIT-NT # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Website
    url: https://www.wetrackit.com.au
  - name: Tracking Dashboard
    url: https://app.wetrackit.com.au
  - name: Devices - Teltonika Support
    check: "tcp-ping"
    url: $DATA_URL
    port: $TELTONIKA_PORT
  - name: Devices - TopFlyTech Support
    check: "tcp-ping"
    url: $DATA_URL
    port: $TOPFLYTECH_PORT
  - name: LEGACY Tracking Dashboard
    url: https://dashboard.wetrackit.com.au

status-website:
  theme: dark
  cname: status.wetrackit.com.au
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: We Track IT
  introTitle: "*We Track IT** is the Terrtory's leading telematics provider"
navbar:
    - title: Website
      href: https://www.wetrackit.com.au
    - title: Dashboard
      href: https://app.wetrackit.com.au
    - title: iOS Download
      href: https://apps.apple.com/au/app/we-track-it/id6449930972
    - title: Android Download
      href: https://play.google.com/store/apps/details?id=com.WeTrackITclient.android

